### ISSUE TITLE
How to know that which type of account user(i.e. Work or school, or personal) is logged in using MSAL.

### ISSUE THREAD

**Issue by suniljakhar** [Azure-Samples/active-directory-ios-swift-native-v2#13]
Hi,
I need identify the type of account(i.e. business or personal) based on the user logged in using MSAL framework.

**Comment by gsacavdm** [comment]
Please ask these kinds of questions (not directly an issue with the sample) in StackOverflow using the [azure-active-directory](https://stackoverflow.com/questions/tagged/azure-active-directory) tag
