### ISSUE TITLE
The required app scheme is not registered in the app's info.plist file?

### ISSUE THREAD

**Issue by olavt** [Azure-Samples/active-directory-ios-swift-native-v2#2]
I have successfully modified the sample using my own Azure AD tenant, but when I run it I get the following error:

Unable to create application Error Domain=MSALErrorDomain Code=-42001 "(null)" UserInfo={MSALErrorDescriptionKey=The required app scheme (msal<my app id>) is not registered in the app's info.plist file. Make sure the URI scheme matches exactly "msal<clientID>" format without any whitespaces.}

I did not find any instructions in the README.md about needing to change an entry in info.plist. After a little bit digging I found the entry that needed to be changed. The entry was a bit hidden, since it was a couple of levels down. It would be a good idea to add that to the instructions.

**Comment by brandwe** [comment]
I will add this to the instructions.

**Comment by brandwe** [comment]
Updated with your feedback. Let me know if it is more clear.
