### ISSUE TITLE
pod install fails because Podfile references non-existant 0.2.0 tag in microsoft-authentication-library-for-objc

### ISSUE THREAD

**Issue by ejlofgren** [Azure-Samples/active-directory-ios-swift-native-v2#31]
I get an error running "pod install" 

```
$ pod install
Analyzing dependencies
Pre-downloading: `MSAL` from `https://github.com/AzureAD/microsoft-authentication-library-for-objc`, tag `0.2.0`, submodules `true`

[!] Error installing MSAL
[!] Failed to download 'MSAL'.
```

The podfile has:

`pod 'MSAL', :git => 'https://github.com/AzureAD/microsoft-authentication-library-for-objc', :tag => '0.2.0', :submodules => true
`

But there is no 0.2.0 tag here:
https://github.com/AzureAD/microsoft-authentication-library-for-objc/tags

`pod install` works if I change to a tag that does exists such as 0.1.3 (but then I get errors like Use of undeclared type 'MSALAccount' when I try to build)

This issue can be closed once https://github.com/AzureAD/microsoft-authentication-library-for-objc/tags has a 0.2.0 tag.

**Comment by oldalton** [comment]
0.2.0 has now been released: https://github.com/AzureAD/microsoft-authentication-library-for-objc/releases/tag/0.2.0
Sorry for a delay!

**Comment by ejlofgren** [comment]
No worries, thanks!
