### ISSUE TITLE
How do i get the following data

### ISSUE THREAD

**Issue by samuelnoye** [Azure-Samples/active-directory-ios-swift-native-v2#91]
1. Refresh token
2. Login hint

**Comment by ameyapat** [comment]
@samuelnoye The refresh token is saved in the keychain. As a caller of MSAL you do not need to handle refresh token, the MSALResult returned : https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALResult.html contains the access token and idtoken. login_hint is what you supply in MSALInteractiveParameters see : https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALInteractiveTokenParameters.html#/Configuring%20MSALInteractiveTokenParameters

**Comment by kaisong1990** [comment]
Closing as no active conversation
