### ISSUE TITLE
SFSafariViewController is not returning to iOS app 

### ISSUE THREAD

**Issue by dhirsumit** [Azure-Samples/active-directory-ios-swift-native-v2#92]
Hi, 

I am working on the MSAL SSO login when I set the .safariViewController in webViewParameters and try to login then it is not returning to the iOS App, it just show DONE button on SafariViewController.  I have also checked the other thread and everyone is saying that we need to use below line :=

 func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
            print("Received Callback in App delegate \(options)  \(url)")
            return MSALPublicClientApplication.handleMSALResponse(url, sourceApplication: options[UIApplication.OpenURLOptionsKey.sourceApplication] as? String)
        }
        
I have also added above code and my redirect url is also correct but still it is not working.

Can anyone help me on this issue.

Code : = 

 self.webViewParameters = MSALWebviewParameters(authPresentationViewController: self)
 self.webViewParameters?.webviewType = .safariViewController
 self.webViewParameters?.presentationStyle = .fullScreen
 
 info.plist:==
 
 ```
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>msauth.$(PRODUCT_BUNDLE_IDENTIFIER)</string>
			</array>
		</dict>
	</array>
	<key>LSApplicationQueriesSchemes</key>
	<array>
        <string>msauth</string>
		<string>msauthv2</string>
		<string>msauthv3</string>
	</array>
```
 
 Thanks in advance

**Comment by mipetriu** [comment]
Hi @dhirsumit - apologies for the delay in replying here. Could you share MSAL logs of the issue occurring?

Also, are you able to use WKWebview or ASWebAuthenticationSession?

**Comment by jasoncoolmax** [comment]
close due to lack of activity.
