### ISSUE TITLE
Problem Building the Clone

### ISSUE THREAD

**Issue by fgfreeman5** [Azure-Samples/active-directory-ios-swift-native-v2#94]
Hello, I have had some problems trying to set up my xcode environment after importing MSAL. Raheem Chisman recommended cloning the entire GitHub and working from there. I have done and tried to debug some of the beginning things such as assigning a team in Signing & Capabilities, but I run into to some warnings and errors when trying to build it. I have attached a screen shot of those. The errors seem to all correlate as one says there are multiple commands to create a file, but then it could not be found later. The other says there are duplicate files. The error message then says it cannot open said file. I have not adjusted the contents of the clone, so I am not sure where these errors are coming from. Let me know the next steps.
<img width="258" alt="Screenshot 2024-07-30 at 10 44 43 AM" src="https://github.com/user-attachments/assets/01099fcf-a9d7-424b-be7a-7e707866962c">

**Comment by mipetriu** [comment]
Hi @fgfreeman5 - to start, do you mind double-checking that you completed the initial setup steps for the MSAL iOS sample?

1. After cloning, run `pod install` in the directory that holds the podfile
2. Open the project using the .xcworkspace file

**Comment by fgfreeman5** [comment]
Hi @mipetriu , I deintegrated and reinstalled with the pod command but still have an issue the MSAL.framework file. It is currently the only error I have which is an improvement, but it still has a few warnings. Is there any chance we can hop on a call to do this together? Here is the error screenshot again.
<img width="269" alt="Screenshot 2024-08-06 at 1 05 28 PM" src="https://github.com/user-attachments/assets/14219192-ae7c-439c-962c-4f59e5753d54">

**Comment by mipetriu** [comment]
Hello @fgfreeman5, apologies for the extremely late follow up here. I will close this issue for now due to its inactivity, but feel free to re-open if you are still seeing issues.
